CREATE TABLE IF NOT EXISTS PRODUCT_PRICES (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    BRAND_ID INTEGER,
    START_DATE TIMESTAMP,
    END_DATE TIMESTAMP,
    PRICE_LIST DOUBLE,
    PRODUCT_ID BIGINT,
    PRIORITY INTEGER,
    PRICE DOUBLE,
    CURRENCY VARCHAR(30));